name = "MatrixEquations"
uuid = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
authors = ["Andreas Varga <varga.andreas@gmail.com>"]
version = "2.5.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"

[extras]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BandedMatrices = "1.9"
DoubleFloats = "1.3"
GenericLinearAlgebra = "0.3"
GenericSchur = "0.5"
IterativeSolvers = "0.9"
JLD2 = "0.5"
KrylovKit = "0.9"
LinearAlgebra = "1"
LinearMaps = "3.3"
Random = "1"
SparseArrays = "1"
Test = "1"
julia = "1.10"

[targets]
test = ["BandedMatrices", "GenericSchur", "GenericLinearAlgebra", "DoubleFloats", "IterativeSolvers", "JLD2", "KrylovKit", "Random", "SparseArrays", "Test"]
