name = "MatrixEquations"
uuid = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
authors = ["Andreas Varga <varga.andreas@gmail.com>"]
version = "2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"

[compat]
julia = "1.3"
LinearMaps = "3.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
