name: CI
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '.github/workflows/TagBot.yml'
      - '.github/workflows/Documentation.yml'
      - 'docs/*'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '.github/workflows/TagBot.yml'
      - '.github/workflows/Documentation.yml'
      - 'docs/*'

permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Tests, Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10' # Current Julia LTS release
          - '1'    # Latest stable Julia 1.x release
          - 'pre'  # Release candidates / pre-releases
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false          